repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: biome-format
        name: biome format
        entry: bunx @biomejs/biome format --html-formatter-enabled=true --css-formatter-enabled=true
        language: system
        types_or: [javascript, html, css]
        pass_filenames: true

      - id: biome-lint
        name: biome lint
        entry: bunx @biomejs/biome lint
        language: system
        types: [javascript]
        pass_filenames: true
