/**
 * build-themes: Read extracted style data and generate theme CSS files.
 *
 * Usage: bun run build:themes
 *
 * Reads:  data/wayback/{theme}/{content_type}/styles.json
 * Outputs: output/themes/twitter-{era}.css
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ExtractedStyles, TwitterEra } from "../lib/types.ts";

const DATA_DIR = resolve(import.meta.dirname, "../../data");
const OUTPUT_DIR = resolve(import.meta.dirname, "../../output/themes");

const ERAS: TwitterEra[] = [
	"twitter-classic",
	"twitter-new",
	"twitter-material",
	"twitter-modern",
];

/**
 * Known fallback values for each era, used when extraction data is incomplete.
 * These are researched baseline values from each Twitter design period.
 */
const ERA_DEFAULTS: Record<TwitterEra, Record<string, string>> = {
	"twitter-classic": {
		"--card-bg": "#ffffff",
		"--card-border": "1px solid #cccccc",
		"--card-border-radius": "5px",
		"--card-padding": "10px",
		"--text-font": '"Lucida Grande", Arial, sans-serif',
		"--text-size": "12px",
		"--text-color": "#333333",
		"--text-line-height": "1.4",
		"--meta-color": "#999999",
		"--meta-size": "11px",
		"--link-color": "#0084b4",
		"--name-font-weight": "bold",
		"--name-size": "14px",
		"--avatar-size": "73px",
		"--avatar-radius": "4px",
		"--engagement-color": "#999999",
	},
	"twitter-new": {
		"--card-bg": "#ffffff",
		"--card-border": "none",
		"--card-border-bottom": "1px solid #e1e8ed",
		"--card-border-radius": "0",
		"--card-padding": "12px 16px",
		"--text-font": '"Helvetica Neue", Helvetica, Arial, sans-serif',
		"--text-size": "14px",
		"--text-color": "#292f33",
		"--text-line-height": "1.5",
		"--meta-color": "#66757f",
		"--meta-size": "12px",
		"--link-color": "#1b95e0",
		"--name-font-weight": "bold",
		"--name-size": "14px",
		"--avatar-size": "48px",
		"--avatar-radius": "4px",
		"--engagement-color": "#66757f",
	},
	"twitter-material": {
		"--card-bg": "#ffffff",
		"--card-border": "1px solid #e1e8ed",
		"--card-border-radius": "0",
		"--card-padding": "12px 16px",
		"--text-font": '"Helvetica Neue", Helvetica, Arial, sans-serif',
		"--text-size": "15px",
		"--text-color": "#14171a",
		"--text-line-height": "1.5",
		"--meta-color": "#657786",
		"--meta-size": "13px",
		"--link-color": "#1da1f2",
		"--name-font-weight": "bold",
		"--name-size": "15px",
		"--avatar-size": "48px",
		"--avatar-radius": "50%",
		"--engagement-color": "#657786",
	},
	"twitter-modern": {
		"--card-bg": "#ffffff",
		"--card-border": "1px solid #eff3f4",
		"--card-border-radius": "16px",
		"--card-padding": "12px 16px",
		"--text-font":
			'"TwitterChirp", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
		"--text-size": "15px",
		"--text-color": "#0f1419",
		"--text-line-height": "1.5",
		"--meta-color": "#536471",
		"--meta-size": "13px",
		"--link-color": "#1d9bf0",
		"--name-font-weight": "700",
		"--name-size": "15px",
		"--avatar-size": "40px",
		"--avatar-radius": "50%",
		"--engagement-color": "#536471",
	},
};

/**
 * Merge extracted styles into the era defaults.
 * Extracted values override defaults where they exist.
 */
function mergeExtractedStyles(
	era: TwitterEra,
	extractedFiles: ExtractedStyles[],
): Record<string, string> {
	const vars = { ...ERA_DEFAULTS[era] };

	// Attempt to map extracted computed styles to our CSS custom properties.
	// This is a best-effort heuristic — the build-themes script provides a
	// scaffold that is then hand-tuned against screenshots.
	for (const styles of extractedFiles) {
		for (const [_selector, props] of Object.entries(styles)) {
			// Background color of the card
			if (props.backgroundColor && props.backgroundColor !== "rgba(0, 0, 0, 0)") {
				vars["--card-bg"] = props.backgroundColor;
			}
			// Text properties from the main content area
			if (props.fontFamily) vars["--text-font"] = props.fontFamily;
			if (props.fontSize) vars["--text-size"] = props.fontSize;
			if (props.color && props.color !== "rgba(0, 0, 0, 0)") {
				vars["--text-color"] = props.color;
			}
			if (props.lineHeight) vars["--text-line-height"] = props.lineHeight;
		}
	}

	return vars;
}

/** Generate a CSS file for one era. */
function generateCss(era: TwitterEra, vars: Record<string, string>): string {
	const sel = `.post[data-theme="${era}"]`;
	const customProps = Object.entries(vars)
		.map(([k, v]) => `\t${k}: ${v};`)
		.join("\n");

	return `/* ${era} theme — generated by build-themes.ts */
/* Hand-tune values against data/wayback/${era}/*/screenshot.png */

${sel} {
${customProps}

\tbackground: var(--card-bg);
\tborder: var(--card-border);
\tborder-radius: var(--card-border-radius);
\tpadding: var(--card-padding);
\tfont-family: var(--text-font);
\tcolor: var(--text-color);
}

${sel} .post-avatar img {
\twidth: var(--avatar-size);
\theight: var(--avatar-size);
\tborder-radius: var(--avatar-radius);
\tobject-fit: cover;
}

${sel} .post-display-name {
\tfont-weight: var(--name-font-weight);
\tfont-size: var(--name-size);
\tcolor: var(--text-color);
}

${sel} .post-handle,
${sel} .post-separator,
${sel} .post-timestamp {
\tcolor: var(--meta-color);
\tfont-size: var(--meta-size);
}

${sel} .post-text {
\tfont-size: var(--text-size);
\tline-height: var(--text-line-height);
\tcolor: var(--text-color);
}

${sel} .post-engagement {
\tcolor: var(--engagement-color);
\tfont-size: var(--meta-size);
}

${sel} .post-link a {
\tcolor: var(--link-color);
}

${sel} .post-reply-context {
\tcolor: var(--meta-color);
\tfont-size: var(--meta-size);
}

${sel} .post-quoted {
\tborder: 1px solid var(--meta-color);
\tborder-radius: var(--card-border-radius);
\tpadding: 8px 12px;
\tmargin-top: 8px;
}
`;
}

function main() {
	mkdirSync(OUTPUT_DIR, { recursive: true });

	for (const era of ERAS) {
		const eraDir = resolve(DATA_DIR, "wayback", era);
		const extractedFiles: ExtractedStyles[] = [];

		// Load all extracted styles.json for this era
		if (existsSync(eraDir)) {
			for (const ct of readdirSync(eraDir)) {
				const stylesPath = resolve(eraDir, ct, "styles.json");
				if (existsSync(stylesPath)) {
					const data = JSON.parse(readFileSync(stylesPath, "utf-8"));
					extractedFiles.push(data);
				}
			}
		}

		const vars = mergeExtractedStyles(era, extractedFiles);
		const css = generateCss(era, vars);
		const outPath = resolve(OUTPUT_DIR, `${era}.css`);
		writeFileSync(outPath, css);

		const source =
			extractedFiles.length > 0
				? `merged with ${extractedFiles.length} extracted file(s)`
				: "defaults only (no extracted data yet)";
		console.log(`  ${era}: wrote ${outPath} (${source})`);
	}

	console.log("\nDone. Review and hand-tune the generated CSS against screenshots.");
}

main();
